sudo: false
cache: bundler
language: ruby
sudo: false
before_install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'
script: "bundle exec rake"
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.2.2
  - ruby-head
  - rbx-2
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby-head
  fast_finish: true
branches:
  only:
    - master
