sudo: false

rvm:
  - 2.3.3
  - ruby-head
  - rbx-2
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby-head
  fast_finish: true

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile

script: "bundle exec rake test"

branches:
  only:
    - master

before_install:
  - gem update bundler
